### ISSUE TITLE
How do I view my newly created wiki site with the viewer?

### ISSUE THREAD

**Issue by evolve2k** [peterkeen/sites#4]
Hi I've managed to spin up the app by setting up a few environment variables and running 'rackup' and from there have been able to create a wiki site through your interface and add a couple of pages to it. 

How do I view my newly created wiki site with the viewer? 
I ran:
$ ruby viewer.rb
Sadly Sinatra no understand what's going on :(

How do I start the viewer and view my sites it in development?
What am I missing?

Thanks

Richie

**Comment by peterkeen** [comment]
The only way (currently) to view a site is to set a CNAME in the 'cnames' wiki page and then set that in your hosts file. So for example you can put www.example.com in the 'cnames' wiki page and "127.0.0.1 www.example.com" in /etc/hosts, then visit www.example.com:4567 in your browser. 

This is pretty bad. I'll make some time tomorrow to make an accessible view route.

**Comment by evolve2k** [comment]
Ok thanks

**Comment by peterkeen** [comment]
@evolve2k there's now a private, authenticated view at `/:sitename/view`. Other new things:
- The layout can be a wiki page named `layout` instead of just `layout.erb`
- There's a helper named `static_path` which you should use for asset includes so that they show up properly in the private view.
- Assets can be ERB templates (so you can use the `static_path` helper.
