### ISSUE TITLE
http://sites.bugsplat.info requires authentication

### ISSUE THREAD

**Issue by vlado** [peterkeen/sites#6]
I tried to open http://sites.bugsplat.info from the readme (https://github.com/peterkeen/sites#in-the-wild) but I was asked to authenticate.

**Comment by peterkeen** [comment]
This is by design. `sites.bugsplat.info` powers a bunch of sites for me, including http://bits.petekeen.net. The linked blog post shows some screen shots of the management interface, but really there's nothing to see beyond the interface that GitHub presents for wikis (it's the same code underneath, https://github.com/gollum/gollum).
